services:
  nats:
    image: nats  # Образ NATS
    entrypoint: /nats-server  # Команда запуска сервера внутри контейнера
    ports:
      - "4222:4222"  # Основной порт для взаимодействия с сервером
      - "8222:8222"  # Порт для мониторинга сервера по HTTP
    volumes:
      - ./nats/data:/data  # Путь, по которому NATS-сервер будет хранить данные вне контейнера

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"  # Порт для доступа к NATS NUI
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats